// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrlsofipkkxyqremsfew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpybHNvZmlwa2t4eXFyZW1zZmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzcwMTUsImV4cCI6MjA3Mzg1MzAxNX0.WCaJIZxjNEPGlfhRbaGSkeQKdPvsf6UTw08SOPBvGOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});